name: Update Docs Config
on:
  repository_dispatch:
    types: [update-docs-config]

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # 显式指定当前仓库
          ref: ${{ github.event.client_payload.branch }}
          path: main-repo
          fetch-depth: 0

      - name: Debug environment
        working-directory: ./main-repo  # 关键：锁定操作目录
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Remote branches:"
          git branch -r

      - name: Get Base Config
        uses: actions/checkout@v4
        with:
          repository: Vegetable-SYC/docs-base-config
          path: base-config 

      - name: Merge Config
        working-directory: ./main-repo  # 确保在目标分支目录操作
        run: |
          python "${GITHUB_WORKSPACE}/base-config/update_workflow/sync_config.py" \
            --source "${GITHUB_WORKSPACE}/base-config/base_conf.py.tpl" \
            --target "docs/source/conf.py" \
            --source_req "${GITHUB_WORKSPACE}/base-config/requirements.txt.tpl" \
            --target_req "docs/requirements.txt"

      - name: Commit Changes
        working-directory: ./main-repo  # 必须锁定目录
        run: |
          git config user.name "Docs Bot"
          git config user.email "docs-bot@example.com"
          git add docs/source/conf.py docs/requirements.txt
          
          # 显式指定远程和分支
          git pull origin ${{ github.event.client_payload.branch }}
          git commit -m "Auto-update docs config"
          git push origin HEAD:${{ github.event.client_payload.branch }}